### ISSUE TITLE
Enhancement: Mark track segments as one way

### ISSUE THREAD

**Issue by LiaungYip** [MineMaarten/Signals#16]
I have a rail network consisting of a main loop of track, with spur lines that are also loops.

Occasionally, I find carts that have rammed into each other and stopped.

A way of marking track segments as one-way would prevent this.

**Comment by MineMaarten** [comment]
By having a signal on the loop that already enforces a one-way segment, as carts aren't allowed to be routed backwards past a signal. In any case, collisions shouldn't be happening as that's what the signals are there for to prevent.

Could you explain a bit more, as I probably don't fully understand your situation :P

**Comment by LiaungYip** [comment]
I didn't know that Block Signals are also one-way markers. That's useful information!

> Could you explain a bit more, as I probably don't fully understand your situation :P

It is completely possible that the error exists between the keyboard and chair.

I'll try to produce a minimum reproducible test case next time I open Minecraft.
