### ISSUE TITLE
Patch 1.11.2

### ISSUE THREAD

**Issue by mepeisen** [MineMaarten/Signals#19]
See attached file. My changes seems to work :-)

[Signals.zip](https://github.com/MineMaarten/Signals/files/776983/Signals.zip)

**Comment by mepeisen** [comment]
based on 1.10 branch. Do not know if this is different from master.

**Comment by CplPibald** [comment]
I have created a working jar to port this mod to 1.11.2.   [See release branch here](https://github.com/CplPibald/Signals/releases/tag/v1.11.2-0.5.1)

I started from the patch above to fix the build errors ( Thanks @mepeisen !!!).  Then I fixed a number of crash and logic bugs coming from the switch from `(ItemStack)null` to `ItemStack.EMPTY` to represent an empty stack in 1.11.

**Comment by MineMaarten** [comment]
Thank you both for the effort! However, I have gone straight to 1.12.2, using modmuss' PR: https://github.com/MineMaarten/Signals/pull/30

Sorry for my absence.
