### ISSUE TITLE
Missing a way to automatically set destinations

### ISSUE THREAD

**Issue by githubnemo** [MineMaarten/Signals#21]
To support convenient player transport for multiple destinations it would be nice to have a way to set the destination of a newly spawned cart in an automatic fashion.

Usage example: A player is at station 4 and wants to visit station 2 in a 10-station network by the mere press of a button (spawns cart, cart gets destination 2 set, possibly return station 4).

This is not possible yet since the only way to configure stations is by using the GUI.

Possible ways I can see are

- a command which then can be used with command blocks
- ticket items with the station name written to it which can be applied to the cart with dispensers (not consumed)
- OpenComputers API that opens up the cart capabilities

This would be a great addition for comfortable player transport.

**Comment by githubnemo** [comment]
As an update to this, I tried spawning minecarts using command blocks with the destinations already configured. The NBT tag for the signals minecart destination capability is `ForgeCaps: {signals:minecartDestinationCapability`} and the fields are `destination`, `destIndex` as well as `motorized`. This gives

    /summon MinecartRideable ~ ~ ~ {ForgeCaps:{signals:minecartDestinationCapability:{destination:foo, destIndex: 0, motorized: false}}}

However, this fails as there is no way to escape the `:` in `signals:minecartDestinationCapability` which leads to minecraft converting the key string to `"signals:\"minecartDestinationCapability\""`.

**Comment by MineMaarten** [comment]
The ticket items sound like a great option!

**Comment by Garagoth** [comment]
Any chance for OpenComputers API?

**Comment by MineMaarten** [comment]
Isn't the Ticket + Dispenser solution sufficient?

**Comment by Garagoth** [comment]
How do I use this when I have like 6 destination stations and would like to select them using a button?
Or set of buttons. This is of course for player transport, but when combined with OC being able to read cart inventory (both for items or players inside) would create a powerful combo.

There is no way I can put 6 dispensers around a minecart, maybe it would be possible by a long line of dispensers, detector rails, and gates, a bit of memory and whole lot of redstone...

Or am I missing something?

**Comment by MineMaarten** [comment]
"There is no way I can put 6 dispensers around a minecart, maybe it would be possible by a long line of dispensers, detector rails, and gates, a bit of memory and whole lot of redstone..."
That would be one solution.

Another could be a solution where you use OC to pick a certain Ticket to put into a single dispenser, fire it, and put the Ticket back into storage. That way you only need a single dispenser.

**Comment by Garagoth** [comment]
Um, true, that would involve an OC robot carrying tickets, reading redstone inputs remotely and interacting with dispenser - as only robots can interact with inventories...
Or maybe I will play with cart NBT a bit... will see what bears some fruits :-)

Maybe I could suggest a track that works with OC adapter and allows getting cart data (destinations, inventory, passenger) as well as setting some data (like destinations?) Data track or something like this that exists only when OC is detected.
Or maybe not a track as making a cart stop there will be a bit difficult. So, a block next to tracks similar to light signals or stations, and all tracks could be used to stop cart there or just detect its presence via redstone.

Maybe such OC api could be integrated with station block itself as well...?

**Comment by MineMaarten** [comment]
Hmm I like the sound of that last sentence! I don't feel like adding a new block because it feels like too much work (model, texture, localization, code) for a feature that isn't going to be used often. However, integrating it into an existing block should do the trick!

Could you please put this into a new issue? And include the info you would like to get/set using this? Also, I'd imagine there are already OC hooks/mods to read cart inventory/passengers?
