### ISSUE TITLE
Feature request: Improve deadlocking (Add Chain Signal)

### ISSUE THREAD

**Issue by za3k** [MineMaarten/Signals#23]
Right now, there are a number of situations where a rail track is shared (for example, 0-0 type tracks) and things end up deadlocked unneccessarily.

https://wiki.factorio.com/Rail_chain_signal is one technique to solve this problem.

Happy to post a screenshot of a sample setup if it would help.

**Comment by MineMaarten** [comment]
Added in version 1.1.0 (when it's approved: https://minecraft.curseforge.com/projects/signals/files/2505703 )

**Comment by za3k** [comment]
Awesome! Thanks so much
