### ISSUE TITLE
Feature Request: Two way signals

### ISSUE THREAD

**Issue by brotazoa** [MineMaarten/Signals#25]
A reasonable way to have two way track with signals. See picture for details.
![2017-04-07_16 21 51](https://cloud.githubusercontent.com/assets/14895001/25047683/54d34280-2106-11e7-89c5-2822898b94b1.png)

**Comment by MineMaarten** [comment]
I don't see the use case here? What would add this opposed to a normal bypass, with for example at the top two signals pointing to the left, and at the bottom two signals pointing to the right? And actually, this set-up could deadlock if two carts are routed exactly at the same time and they both decide to go via the bottom part.
