### ISSUE TITLE
insufficient documentation, and suggestion for improving mod usability

### ISSUE THREAD

**Issue by GeekBeam** [MineMaarten/Signals#27]
currently, the Signals mod doesn't state that signals are a unidirectional system, nor does it state that signals NEED to be on the right side of the track (with rails to the left of the signal, facing the side with lights), I believe this is an error in documentation that needs to be explained for the mod to be learned by those whom _are not_ familiar with the way that factorio or OpenTTD do it.

one method of improving such a problem would be to make the direction of the signal automatically orient itself based on the side of the Track it is on, much like Factorio does.

it would _ALSO_ help if the signal block had an arrow that overlaid on the track block to indicate the direction it is pathing carts towards (think of how factorio has the yellow arrows that indicate direction). this would help new players learn how these signals operate much more smoothly.

another utility that would be incredibly useful is, while hovering the mouse cursor over a signal, if that signal could highlight the track blocks that are within is "signal block".

a lot of these suggestions are ideas that already exist within Factorio (which is stated to have been of similar design) so it makes complete sense that this mod would have those.

**Comment by MineMaarten** [comment]
Excellent ideas! I'm for sure going to take a look at Factorio's additions as well as yours. Auto-orienting sounds great, not only for clearness, but also for quickly placing down signals.

**Comment by MineMaarten** [comment]
There you go :) :
![2018-01-20_18 04 56](https://user-images.githubusercontent.com/5345405/35185957-6ef32660-fe0c-11e7-8ce4-ff3441834985.png)
