### ISSUE TITLE
Disable cart hoppers

### ISSUE THREAD

**Issue by josephcsible** [MineMaarten/Signals#41]
You should be able to disable cart hoppers somehow, like you can disable regular hoppers with a redstone signal.

**Comment by MineMaarten** [comment]
Do you have a use case for this? I currently think that simply by the fact it 'enables' as long as there is a cart on top/under it is enough?

**Comment by josephcsible** [comment]
Suppose I wanted to add fuel to carts only if they were already empty or almost empty. I could use another mod to read the inventory via #40, and then turn on redstone if it's full enough.

**Comment by MineMaarten** [comment]
Okay sounds good! I could probably add a button for it. Could be a bit tricky as the block itself also emits redstone, but we'll see.
