### ISSUE TITLE
Automatically add engines to minecarts

### ISSUE THREAD

**Issue by josephcsible** [MineMaarten/Signals#43]
We should add an automated way to install cart engines in minecarts. My suggestion: if a cart hopper is set to interact with engines, and the cart it's pointed at doesn't have an engine, you can pipe one into it and it will install it. If you like this idea, I can write the code and PR it.

**Comment by MineMaarten** [comment]
Sounds good! Also make sure that apart from 'piping into it' using the IItemHandler stuff you've added, it should also work by the native transfer method of the Cart Hopper. So like, an inventory on top with a Cart Engine in it, with the Cart Hopper set to interact with engines, will install the engine in the cart under the hopper.
