### ISSUE TITLE
Add an API to edit cart destinations

### ISSUE THREAD

**Issue by josephcsible** [MineMaarten/Signals#44]
I'm trying to set up Integrated Dynamics to automatically set destinations on minecarts. There aren't any public methods to change destinations (except for the GUI handler), so I currently have to use reflection, which isn't ideal. Can we add an API for controlling this (and similar things)?

**Comment by MineMaarten** [comment]
If I understand you correctly you'd like something like this, properly exposed via the API, which you can retrieve given a certain EntityMinecart? :

`IDestinationCapability{
void setDestinations(String... destinations);
int getTotalDestinations();
int getCurrentDestinationIndex()
void setCurrentDestinationIndex(int index);
}`

Anything else you'd like to see in this? I will most certainly will add this :).
Also in the future when running into something you can't hook into, just let me know, I'm more than happy to expand the API.

**Comment by josephcsible** [comment]
Here's a few other things I can think of (some of these already have reader methods, but need writer methods still):
* Names of station markers (I know setText and getText exist, but these would suddenly break if some other text field were ever added)
* The settings stored in DestinationProviderItems
* hopperMode and interactEngine from TileEntityCartHopper

**Comment by MineMaarten** [comment]
I can do that :)

**Comment by MineMaarten** [comment]
See commits above. I must admit I haven't fully tested the accessors, but it's simple enough. I'm sure you can test it when using the API :).

**Comment by josephcsible** [comment]
One omission I notice: there's still no way to get the list of current destinations. Also, if you want all API access to be wrapped in interfaces, can you add one for getLampStatus, setForceMode, and getForceMode in TileEntitySignalBase?

**Comment by MineMaarten** [comment]
Ah, that one's added shortly.

And yes, I'd like to expose stuff properly, so your code does not break when I decide to refactor stuff. I try to not change signals.api.* content. 

Do note however that 'getLampStatus()' doesn't say everything (for Path Signals it returns 'yellow' most of the time, unless a cart is routed, only then it can know if it should turn red or green). I can expose it though.
