### ISSUE TITLE
Conditional limiter rails

### ISSUE THREAD

**Issue by josephcsible** [MineMaarten/Signals#46]
It would be nice to have rails that acted like normal rails when they were powered, and limiter rails when they aren't. This would let carts through powered rails without slowing down when on, but still stop them correctly when off.

**Comment by MineMaarten** [comment]
This is a simple enough change to add to the current Limiter Rail, and as they shouldn't be really powered in current worlds not really a breaking change either.

**Comment by josephcsible** [comment]
Looks good, thanks! I'm going to look into adding some kind of visual indicator of if they're receiving power, like vanilla powered rails do.

**Comment by MineMaarten** [comment]
They already do ;). In fact, in the 'old' versions they already visually showed that they were powered, but they simply ignored the signal.
