### ISSUE TITLE
Add a third light to signals

### ISSUE THREAD

**Issue by josephcsible** [MineMaarten/Signals#47]
Can we add a third light to signals? It would be a yellow light meaning that its block is clear but the next signal is red, or equivalently, that the signal would be red if it were a chain signal. This would be cosmetic only, and would provide redstone power just like green signals do now.

**Comment by MineMaarten** [comment]
I don't really like the idea of using the lights which are purely functional indicators for cosmetic purposes.. I'm already using a constant yellow light for signals to indicate a Chain Signal has claimed the block in front of the signal.
