### ISSUE TITLE
RaytraceResult Not Being Null Checked

### ISSUE THREAD

**Issue by InsomniaKitten** [MineMaarten/Signals#58]
RayTraceResult is not being null checked at [ClientEventHandler.java#L98](https://github.com/MineMaarten/Signals/blob/master/src/com/minemaarten/signals/client/ClientEventHandler.java#L98); this causes an NPE in certain cases.

**Mod version:** [1.12.2-1.2.1-4](https://minecraft.curseforge.com/projects/signals/files/2522279)
**Stacktrace:** [pastebin/Jvci5VAg](https://pastebin.com/raw/Jvci5VAg)

**Comment by MineMaarten** [comment]
Hmpf I did specifically test with this and it worked fine in testing.. Plus that there's a MISS enum value in RayTraceResult... Oh well, new build incoming. Thanks for the report.
