### ISSUE TITLE
World Corruption Crash

### ISSUE THREAD

**Issue by D3nnis3n** [MineMaarten/Signals#64]
While making a underground metro we got that crash:
https://gist.github.com/D3nnis3n/699acb3820e5a7e66379b6a2892ada2f

Since then the server crashes on every restart with the same crash.

**Comment by D3nnis3n** [comment]
Also present on build 11 which was just released.

**Comment by MineMaarten** [comment]
Hmm you're sure it's still occuring in build 11? If so, I expect a different crash log at least, because this exact crash isn't possible with build 11?

**Comment by D3nnis3n** [comment]
Could fix it by placing blocks on the location where the signals were before and then load up the new Signals version 11.

**Comment by MineMaarten** [comment]
Hmm I'm still curious about the new crash report you got with build 11...

**Comment by D3nnis3n** [comment]
I did not save it unfortunately as it looked exactly the same on my look in
the console. I'm sorry.

MineMaarten <notifications@github.com> schrieb am Mo., 30. Apr. 2018, 05:38:
