### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by OldManCraft** [MineMaarten/Signals#69]
Forge 2726
Version 1.3.3-12
Sample:
02.07 18:38:15 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:15 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:16 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:16 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:17 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:18 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:18 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:19 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:20 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:20 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:20 [Server] Server thread/INFO [signals]: 20605, updates: 0
02.07 18:38:22 [Server] Server thread/INFO [signals]: 20605, updates: 0

**Comment by cpw** [comment]
Yup, seen on Forgecraft as well. Please fix :D

**Comment by MineMaarten** [comment]
Whoops :/ Fixing in a sec
