### ISSUE TITLE
Blocks break with one click

### ISSUE THREAD

**Issue by TOLoneWolf** [MineMaarten/Signals#7]
You can break every block added by signals in one hit with your empty fist. This makes it very easy to break your rail lines with a miss click and it doesn't drop the item back because you used the wrong tool to do it (didn't use a pick).

Make it take longer to break with wrong tool (a second or 2 should do), and maybe also a slight delay with the correct tool.

PS - Nice simple rail mod.

**Comment by MineMaarten** [comment]
Fixed in 0.3.0
