### ISSUE TITLE
Server Extreme CPU usage on Login

### ISSUE THREAD

**Issue by ChosenArchitect** [MineMaarten/Signals#74]
Pack - FTB Revalations 2.2 beta
Mod - Signals-1.12.2-1.3.4-14-universal
Issue - Extreme CPU usage on server login
Fix - Disabled the mod
![capture](https://user-images.githubusercontent.com/35053440/42466393-6ba18130-8374-11e8-89cd-f23c8ae85d00.PNG)
![test](https://user-images.githubusercontent.com/35053440/42466394-6bb387ea-8374-11e8-990a-85441e027852.PNG)
![2018-07-09 1](https://user-images.githubusercontent.com/35053440/42466411-788bb942-8374-11e8-9512-83212429757c.png)

Client Snapshot Login
[snapshot-1531153948724.zip](https://github.com/MineMaarten/Signals/files/2177359/snapshot-1531153948724.zip)

**Comment by MineMaarten** [comment]
Thanks for the detailed report with profiler report :).

When logging in, the server will send the rail network to the client, and the client will build this. This is a process which should happen in the background. However, the way it is currently set up, it drains all CPU resources it can find, which you're noticing.

Hoping to prevent this, I have prepared a build which only allows this background process a limited amount of CPU resources. Could you try http://jenkins.k-4u.nl/view/MineMaarten/job/Signals/18/ ? If you can let me know if this solves it for you, that would be much appreciated :)

**Comment by ChosenArchitect** [comment]
With this being such a large scale server I will have to do the testing when FTB Rev updates to 2.3 and they should be using the latest build of your mod. I will report back if I find any problems 👍

**Comment by MineMaarten** [comment]
I'll be closing this now, feel free to ask to reopen when the issue still arises.
