### ISSUE TITLE
Games crashes when powering a "Powered Rail"

### ISSUE THREAD

**Issue by LTNightshade** [MineMaarten/Signals#79]
When i power a "Powered Rail" the game often crashes

I'm playing the FTB Revelation Modpack in Version 2.2.0

Signals Mod : 1.12.2-1.3.4-14

Crashlog : https://pastebin.com/L3gDbCkX

FTB-Revelation Issus: https://github.com/FTBTeam/FTB-Revelation-2/issues/93

**Comment by MineMaarten** [comment]
Thanks for the report. As soon it is approved, you can grab this fix https://minecraft.curseforge.com/projects/signals/files/2602045
