### ISSUE TITLE
ConcurrentModificationException thrown when using Block Randomizer from Cyclic

### ISSUE THREAD

**Issue by ParadoxBomb** [MineMaarten/Signals#81]
See also https://github.com/PrinceOfAmber/Cyclic/issues/906

Minecraft version:
1.12.2

Forge version:
14.23.4.2750

Signals version:
1.3.11-22

When using Cyclic's Block Randomizer on a floor of mixed Chisel Factory Blocks, something in Signals seems to catch... something, and the server crashes with a ConcurrentModificationException. The issue seems to be intermittent but repeatable.

Crash Report: 
VanillaFix was used to capture the crash log
https://paste.dimdev.org/ateyadunoh.mccrash

**Comment by MineMaarten** [comment]
This is a bug in Cyclic, added additional info in the other issue.
