### ISSUE TITLE
Crash when attempting to pregenerate world v.1.12.2-1.3.12-23

### ISSUE THREAD

**Issue by DrZoddiak** [MineMaarten/Signals#85]
When attempting to pre-generate my world I come to a crash with this report
https://gist.github.com/DrZoddiak/9c5aa1b2355332979120405ac041d367

I asked about the report and I was told this
https://gyazo.com/115194eccf313e6efef0eccd6cc65861

Debug log:
https://gist.github.com/DrZoddiak/dddd6096477fb1329e72a6a20d223823
Latest log:
https://gist.github.com/DrZoddiak/3e25262d4e0aea4804b9abe0970d7fc6

**Comment by MineMaarten** [comment]
Thanks for the report! Sorry for the late reply, I try to find time in weekends like these :).

As a workaround (if you haven't done this yet), you could pregen the chunks without having Signals installed, and then add Signals afterwards. You should not get this problem.

As for a fix, I would like to reproduce your situation, so I would like to pregen a world. I'm not really familiar with which mods to use for this, or which mod in your modlist is responsible for this so I can look up instructions. Could you give some insights?

As for the Discord response, generated rails shouldn't be be updated by default, only when they become part of a rail network (using Signal blocks). This has changed somewhat recently, but is also included in the version you are using currently. As for updating the carts, yes this happens with worldgenned carts (like in mineshafts), though as soon as the chunks unload they shouldn't have impact on TPS anymore.

**Comment by DrZoddiak** [comment]
The pre-generator I used was using sponge generation methods, and using nucleus for the "pre-gen"
https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2
https://ore.spongepowered.org/Nucleus/Nucleus/versions
Just toss both of those into the mods folder
and then you _should_ be able to run (with OP) `/world border set x` and `/world border gen -a --save 2m`
That should set the border x distance in diameter (I did 20,000) and then generate using -a (aggressive memory, optional, but it'll go faster simply just uses a large portion) and --save (saves the world at x intervals, I used 2 minutes)

As an additional note as a workaround I had reverted a version of the modpack I'm using (FTB Revelations) which uses v.1.12.2-1.3.11-22 and had no crashing issues. So I would think it's fair to say it's likely a change between the two versions.

**Comment by MineMaarten** [comment]
I'm quite sure while pregenerating, the tick time slowly creeped up to the 60 seconds, as a result of keeping updating unloaded minecarts (that are generated in mineshafts). Now these unloaded minecarts shouldn't be updated anymore, resolving this problem.

Version 1.3.13 which includes the fix will be on Curse shortly! Thanks for the report!
