### ISSUE TITLE
Feature request: turn off chunkloading when player is offline.

### ISSUE THREAD

**Issue by ttamttamS** [MineMaarten/Signals#88]
Hello, I'm working on a server right now and I'm trying to reduce the number of loaded chunks. I was wondering if it would be feasible to add an option that would stop carts from loading chunks if the owner is offline. Or alternatively, an option to stop loading if all players are offline. Thanks for the wonderful mod!

**Comment by MineMaarten** [comment]
Hm I'm not sure if it's doable in a clean way, it sounds more like something for Forge / another mod, and this is why:

I am already hooking into player-bound chunk load mechanics, which then allows you to configure the max amount of chunkloaded chunks per player in the Forge config. I'm sure this can be extended by another mod (if that mod does not exist already) to add configuration options to unload when the player is not on the server

**Comment by ttamttamS** [comment]
Makes sense, I know chicken chunks has managed to figure out how to do this, but it makes sense that a chunk loading would be able to put more time and resources into, well, chunkloading. Thanks for your work into this mod! It really is a must have, especially with no foreseeable release for railcraft.
