### ISSUE TITLE
Routing doesnt seem to work

### ISSUE THREAD

**Issue by robotbrain** [MineMaarten/Signals#9]
I have what is roughly a t-junction, similar to what is shown on the IGW for path signals, and the switches aren't changing at all. (all vanilla except for signals)

**Comment by MineMaarten** [comment]
Does reloading the world fix anything? And if not, screenshots/world download so I can try to reproduce?

**Comment by robotbrain** [comment]
Happened in 3 different worlds, i I'll get a world download soon
