### ISSUE TITLE
Method to force direction of a rail

### ISSUE THREAD

**Issue by nunavailabul** [MineMaarten/Signals#90]
Is there already a method to force the direction of a rail? I am having problems with pathing where a cart chooses the wrong entrance into a loop and either stops or goes back the way it came.

If it does not exist could this be a feature request?

Ty for the mod in any case such a simple mod providing so much extensibility.

**Comment by MineMaarten** [comment]
Signals themselves enforce a direction, so carts shouldn't be routed the other way if you have a signal.
