### ISSUE TITLE
[1.12.2] Server tick loop crash when pathfinding

### ISSUE THREAD

**Issue by crysthala** [MineMaarten/Signals#91]
I've built some small, simple tracks in test worlds for my custom pack, and this looks like great fun. Unfortunately, I am getting a crash that appears to be related to pathfinding. I can have signals and station markers without issue, but if I actually set destinations on a cart, crashy things start happening. The cart seems to get to the first stop fine, but the game crashes shortly thereafter.

Forge 14.23.5.2772
Java 1.8.0-181
It first happened with version 1.3.13-28 of Signals. I tried the beta 1.4.0-29 and it still occurred. Thought maybe it was bad mod mojo, tested it in an empty profile with no other mods. Still crashed.

It's dangerous to bugtest alone! Here, take these:
[crash-2018-11-24_05.50.29-server.txt](https://github.com/MineMaarten/Signals/files/2612218/crash-2018-11-24_05.50.29-server.txt)
[debug.log](https://github.com/MineMaarten/Signals/files/2612219/debug.log)

And here are some images of the accompanying track, in case that's relevant:
![2018-11-24_05 53 27](https://user-images.githubusercontent.com/8258548/48967908-4c1ab700-efad-11e8-81c7-1e561aebe584.png)
![2018-11-24_05 53 56](https://user-images.githubusercontent.com/8258548/48967962-dfec8300-efad-11e8-9c99-e6f277cbddfe.png)

**Comment by MaartenKok8** [comment]
Resolved in 1.4.1. Thanks for the report!
