### ISSUE TITLE
Signals stops working when no player is logged in into server

### ISSUE THREAD

**Issue by fipil** [MineMaarten/Signals#92]
Hi,
we're using Signals together with Railcraft on our multiplayer server 1.10.2. Everything works fine, without problems until someone is logged in on the server.  Trains stops on red signals, routing finds a proper way, everything is perfect. Problem is whenever we all left the server. After some time, when we log in back, we usually find some traffic jams, often some train has been routed to opposite direction. Such never happends when at least one player is logged in to the server.
Note that we use the admin worldspike carts in each train, so trains can travel alone - it loads chunks itself.
MineMaarten, please, can you help me? Your mod is brilliant, it was my dream, because I love MC, TTD and Mashinky. So the wrong behaviour makes me very trapped.
Maybe it's a bug which you already solved in some later version? Unfortunately we need MC 1.10.2, because there is not Railcraft for the higher MC version.
I'm programmer and I've already an experience with programming MC Forge, so please, if you don't have time to solve the issue, can you point me to right direction? Maybe I can correct the issue myself?
Thank you!
Fipil.

**Comment by MineMaarten** [comment]
Hey,

Thanks for your interest in the mod! The version of Signals in MC 1.10 relied on the entire rail network to be always fully chunkloaded. This has been changed in MC 1.12, but required a big rewrite of the mod. I'm definately not backporting it to 1.10, and it's too much work to simply point towards the right direction I'm afraid...

https://minecraft.curseforge.com/projects/signals/files/2552172

For now chunkloading the entire rail network (not just the carts) should be your workaround..
